# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eTurist' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eTurist
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'SDWebImage', '~>4.4.2'
  pod 'IQKeyboardManagerSwift'
  pod 'Swinject'
  pod 'lottie-ios'
  pod 'HCSStarRatingView', '~> 1.5'

end
